# Generated by Django 5.1.2 on 2024-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('languages_spoken', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('desired_job_title', models.CharField(max_length=100)),
                ('job_category', models.CharField(blank=True, choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('HR', 'HR')], max_length=100)),
                ('location_preference', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('highest_education_level', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('skills', models.TextField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('soft_skills', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance')], max_length=50)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_availability', models.CharField(max_length=100)),
                ('preferred_working_hours', models.CharField(max_length=100)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('preferred_job_benefits', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('how_did_you_hear_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('availability_to_start', models.CharField(max_length=100)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('consent_to_terms', models.BooleanField(default=False)),
                ('receive_job_alerts', models.BooleanField(default=True)),
                ('profile_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
