# Generated by Django 5.1.2 on 2024-11-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirantregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Aspirant',
        ),
    ]
