# Generated by Django 5.1.2 on 2024-11-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0002_aspirantregistration_delete_aspirant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('languages_spoken', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('desired_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('location_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('highest_education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('employment_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance')], max_length=50, null=True)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('work_availability', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_working_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('terms_and_conditions', models.BooleanField(default=False)),
            ],
        ),
    ]
