# Generated by Django 5.1.2 on 2024-11-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0003_aspirantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantprofile',
            name='aspirant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='aspirant.aspirantregistration'),
        ),
    ]
