# Generated by Django 5.1.2 on 2024-11-15 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0005_application_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied_users',
            field=models.ManyToManyField(blank=True, related_name='appliedjobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
