# Generated by Django 5.1.2 on 2024-11-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0007_aspirantregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspirant.job'),
        ),
    ]
