# Generated by Django 5.1.2 on 2024-11-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0008_alter_application_job'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('aspirant', 'job')},
        ),
    ]
