# Generated by Django 5.1.2 on 2024-11-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0010_rename_application_jobapplication_and_more'),
        ('recruiter', '0006_remove_job_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
