# Generated by Django 5.1.2 on 2024-11-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_job_applied_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applied_users',
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='recruiter.recruiterregistration'),
        ),
    ]
