# Generated by Django 5.1.2 on 2024-11-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_remove_job_applied_users_job_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
    ]
